system:
 plant: chrono
 params:
  step_size: 0.01
  
 flags:
  system_shutdown: false

 chrono:
  namespace: chrono
  flags:
   initialized: false
   gui: true

 planner: default
 default:
  flags:
   initialized: true
