vehicle:
 common:
  m: 0.0
  Izz: 0.0
  la: 0.0
  lb: 0.0

 vehicle_description:
  robotNamespace: hmmwv
  robotName: hmmwv  # NOTE cannot change, will break vehicle.launch because this is hardcoded in
  frameName: map
  ground_truth_topic: base_pose_ground_truth

  # mesh parameters
  scale_factor: 0.2
  mesh_mode: 1

  # vehicle geometry
  base_link: base_link
  base_width: 1.9
  base_length: 3.3
  base_height: 1.2
  base_clearance: 0.5

  # wheels
  wheel_radius: 0.393
  wheel_width: 0.1
  wheel_mass: 2.5
  la: 1.6
  lb: 1.7
  wheel_base: 1
  mu1: 0.9
  mu2: 0.9
  minDepth: 0.005
  kp: 1e8

  # LiDAR properties
  lidar_z: 1.4
  lidar_x: 1.75
  topic: lidar_points

 nloptcontrol_planner:
  # vehicle Limits
  # x_min, x_max, y_min, y_max found in planner config file
  sa_min: -0.5235983333333333 #  -30*3.14159/180
  sa_max: 0.5235983333333333 #  30*3.14159/180
  psi_min: -6.28318
  psi_max: 6.28318
  u_min: 0.01
  u_max: 29.
  ax_min: -2.
  ax_max: 2.
  sr_min: -0.0872663888888889  #-5*3.14159/180
  sr_max: 0.0872663888888889   #5*3.14159/180
  jx_min: -5.
  jx_max: 5.

  # define model parameters
  la: 1.5775        # distance from CoG to front axle
  lb: 1.7245        # distance from CoG to rear axle
  m: 2.6887e+03
  Izz: 4.1101e+03
  FzF0: 1.3680e+04
  FzR0: 1.2696e+04
  dFzx_coeff: 705.
  KZX: 705.
  KZYR: 1040.

  # defines polynominal for acceleration bounds
  AXC: [-0.000128015180401862,0.00858618595422724,-0.225657108071454,3.08283259993589,-0.000138537090018958,0.00684702729623608,-0.120391102052425,-3.55886697370079]

  # tire parameters
  FZ0: 35000.0
  PCY1: 1.5874               #Shape factor Cfy for lateral forces
  PDY1: 0.73957              #Lateral friction Muy
  PDY2: -0.075004            #Variation of friction Muy with load
  PEY1: 0.37562              #Lateral curvature Efy at Fznom
  PEY2: -0.069325            #Variation of curvature Efy with load
  PEY3: 0.29168              #Zero order camber dependency of curvature Efy
  PKY1: -10.289              #Maximum value of stiffness Kfy/Fznom
  PKY2: 3.3343               #Load at which Kfy reaches maximum value
  PHY1: 0.0056509            #Horizontal shift Shy at Fznom
  PHY2: -0.0020257           #Variation of shift Shy with load
  PVY1: 0.015216             #Vertical shift in Svy/Fz at Fznom
  PVY2: -0.010365            #Variation of shift Svy/Fz with load

  Caf: -8.4138e+4            # cornering stiffness--front axle (N/rad)
  Car: -7.8126e+4            # cornering stiffness-- rear axle (N/rad)
  Fy_min: -7500
  Fy_max: 7500

  # solver parameters
  Fz_min: 1000.
  Fz_off: 100.
  # NOTE: a_t and b_t are calcuated in src/Three_DOF/parameters.jl in VehicleModels.jl

 chrono:
  control:
   thr: 0.0
   brk: 0.0
   str: 0.0

  state:
   t: 0.0
   x: 0.0
   yVal: 0.0
   ux: 0.0 #Vx
   v: 0.0 #Vy
   ax: 0.0
   psi: 1.57079632679 #yaw
   theta: 0.0 #pitch
   phi: 0.0 #roll
   r: 0.0 #yaw rate
   sa: 0.0

  ros_base_planner:
   traj:
    t: [0.0 0.0 0.0 0.0 0.0 0.0]
    x: [0.0 0.0 0.0 0.0 0.0 0.0]
    yVal: [0.0 0.0 0.0 0.0 0.0 0.0]
    sa: [0.0 0.0 0.0 0.0 0.0 0.0]
    thr: [0.0 0.0 0.0 0.0 0.0 0.0]
    brk: [0.0 0.0 0.0 0.0 0.0 0.0]

  nloptcontrol_planner:
   traj:
    t: [0.0 5.0]
    x: [200.0, 200.0]
    yVal: [0.0, 50.0]
    sa: [0.0 0.0]
    thr: [0.0 0.0]
    brk: [0.0 0.0]

  default:
   traj:
    t: [0.0 2.0 3.0 4.0 5.0]
    x: [199.989, 199.989, 199.989, 199.985, 199.959, 199.882, 199.715, 199.463, 199.19, 198.992,198.943, 198.724, 198.15, 197.127, 195.701, 194.168, 192.939, 192.241, 192.085, 191.439, 190.569, 190.919, 193.045, 195.393, 196.104]
    yVal: [0.0381458, 0.0433473, 0.0791504, 0.263096, 0.797216, 1.82058, 3.2641, 4.85751, 6.24848, 7.12986, 7.34851, 8.22214, 10.2693, 13.3859, 17.2667, 21.3574, 24.9169, 27.1953, 27.7639, 30.3015, 35.8857, 43.2004, 49.8849, 53.9329, 54.8829]
    sa: [0.0 0.0 0.0 0.0 0.0 0.0]
    thr: [2.5 2.5 2.5 2.5 2.5 2.5]
    brk: [0.0 0.0 0.0 0.0 0.0 0.0]
