case:
 goal:
  x: 200.
  yVal: 125.
  v: 10
  psi: 1.5701
  tol: 4

 actual:
  X0:
   x: -115.0
   yVal: -120.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 0.0
   ax: 0.0
  obstacle:
   num: 1
   radius: [1.]
   length: [5.]
   x0: [200]
   y0: [50]
   vx: [0]
   vy: [0]

 path:
  switch_rate: 0.1
  path_1:
   x: [0,10]
   y: [-122,-122]

  path_2:
   x: [0,10]
   y: [-120,-120]

