case:
 goal:
  x: 0.
  yVal: 125.
  psi: 1.5701
 actual:
  X0:
   x: 0.0
   yVal: 0.0
   v: 0.0
   r: 0.0
   psi: 1.57079632679
   sa: 0.0
   ux: 17.0
   ax: 0.0
  obstacle:
   num: 1
   radius: [1.]
   length: [5.]
   x0: [0]
   y0: [50]
   vx: [0]
   vy: [0]
