sudo: required
language: ruby
services:
  - docker
before_install:
  - sh build.sh
#  - docker build -t mavs/sinatra .
#  - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
#  - docker ps -a
#  - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
script:
  - sh run.sh
  - catkin_make clean
  - roslaunch system demoA.launch
