system:
 planner: nlopcontrol_planner
 params:
  goal_tol: 4
  step_size: 0.001
 flags:
  goal_attained: false
  initialized: false
  paused: true
  system_shutdown: false

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   postion_update_external: true
   obstacles_initialized: false

 nloptcontrol_planner:
  namespace: nlopcontrol_planner
  flags:
   running: true
   initialized: false
   known_environment: true
   3DOF_plant: true

 obstacle_detector:
  flags:
   running: false
   initialized: false

 chrono:
  namespace: chrono
  flags:
   initialized: false
   gui: true
