system:
 planner: ros_base_planner
 params:
  goal_tol: 4
  step_size: 0.001
 flags:
  goal_attained: false
  initialized: false
  paused: false
  system_shutdown: false
  
 vehicle_description:
  flags:
   postion_update_external: true
   lidar_initialized: false
   obstacles_initialized: false
 ros_base_planner:
  nameSpace: ros_base_planner
  flags:
   initialized: false
   known_environment: true
   goal_known: true
 chrono:
  namespace: chrono
  flags:
   running: true
   initialized: false
   gui: true
   path_follower: true
