system:
 vehicle_description:
  flags:
   postion_update_external: true
   lidar_initialized: false
   obstacles_initialized: false
 nloptcontrol_planner:
  nameSpace: nloptcontrol
  flags:
   initilized: false
   known_environment: true
   3DOF_plant: true
   goal_attained: false
 chrono:
  namespace: chrono
  flags:
    initialized: false
 ros_global_planner:
  namespace: ros_global_planner
  flags:
   initialized: false
 planner: ros_global_planner
