system:
 planner: nlopcontrol_planner
 plant: chrono
 params:
  step_size: 0.01
 flags:
  goal_attained: false
  initialized: false
  paused: true

 shutdown:
  flags:
   running: true
   initialized: false
  params:
    shutdown_initiation_flags: ["system/flags/goal_attained", "/vehicle_collided"]
    shutdown_completion_flags: []

 nloptcontrol_planner:
  namespace: nlopcontrol_planner
  flags:
   running: true
   initialized: false
   known_environment: true

 flags:
  system_shutdown: false

 chrono:
  namespace: chrono
  flags:
   initialized: false
   running: false
   gui: true
