system:
 planner: ros_base_planner
 plant: chrono
 params:
  step_size: 0.001
 flags:
  goal_attained: false
  initialized: false
  paused: true
  override_shutdown_hook: false
  data_logging_completed: true

 shutdown:
  flags:
   running: true
   initialized: false
  params:
    shutdown_initiation_flags: ["system/flags/goal_attained"]
    shutdown_completion_flags: ["system/flags/data_logging_completed"]

 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   postion_update_external: true

 ros_base_planner:
  nameSpace: ros_base_planner
  flags:
   running: true
   initialized: false
   known_environment: true
   goal_known: true

 chrono:
  namespace: chrono
  flags:
   running: true
   initialized: false
   gui: true
   path_follower: true
